### ISSUE TITLE
Determine a shortcut to change brush size when in extreme zoom

### ISSUE THREAD

**Issue by PotassiumK** [DDMAL/Pixel.js#111]
There are many ways to implement this functionality. Which one would be best for Pixel?
Photoshop uses the following: Control + Option (Mac) – drag left/right in order to decrease/ increase brush size.
Autodesk Sketchbook and other graphic tools often also allow long press on brush tool selection to allow brush size change. This is often the option for tablets/mobile platforms.

To be discussed.

**Comment by zeyadhazem** [comment]
On right click and drag @PotassiumK Also make sure to lock the cursor in place (since we're going to replace the cursor with a circle, the circle should itself become bigger or smaller)
