### ISSUE TITLE
Typing when renaming layers selects corresponding tools on hotkey press

### ISSUE THREAD

**Issue by PotassiumK** [DDMAL/Pixel.js#113]
Possible solutions: 
1. Change hotkeys to require another key press as well. Ex.: Ctrl + B for brush instead of only B.
2. Disable hotkeys listener when changing layer names.

**Comment by zeyadhazem** [comment]
Still not fixed

**Comment by PotassiumK** [comment]
hnnnggg should've referenced this when pushing the code that removed the above changes
