### ISSUE TITLE
Copy elements in one layer and move them to another layer

### ISSUE THREAD

**Issue by PotassiumK** [DDMAL/Pixel.js#138]
If elements are mis-classified onto the wrong layer, they may already be separated from the background. It would save time to simply select the elements from one layer, copy them onto the correct layer and then delete the elements from the wrong layer.

**Comment by PotassiumK** [comment]
On hold until #103 is fixed, as it will change the way layers are implemented and how copying is implemented.

**Comment by zeyadhazem** [comment]
Fixed in https://github.com/DDMAL/Pixel.js/commit/7d00b06054c2a25349c1cbae3d43d39ef6b6bdf9
