### ISSUE TITLE
Cannot deactivate Pixel.js in brush/eraser tool mode

### ISSUE THREAD

**Issue by PotassiumK** [DDMAL/Pixel.js#155]
Due to the change in cursor, when brush tool or eraser tool are selected, Pixel does not react to the cursor clicking the plugin icon.

It still works with the other tools.

**Comment by zeyadhazem** [comment]
It might be because the z-index of the cursor div is higher than the one for the plugin icons (thus the mouse click is applied to the cursor div instead of the icon). Try changing that in the css, might work
