### ISSUE TITLE
Adapt wand plugin to Pixel.js

### ISSUE THREAD

**Issue by PotassiumK** [DDMAL/Pixel.js#168]
There is a functional algorithm of the magic wand tool for OpenLayers. The idea is to adapt the algorithm to Pixel.js without using open layers in any way.

**Comment by PotassiumK** [comment]
Currently, the `wand.js` code is a non-ol implementation that needs to be updated to work with the rest of the code.

**Comment by zeyadhazem** [comment]
duplicate of #78
