### ISSUE TITLE
Fracture and recombine large image uploads without losing data

### ISSUE THREAD

**Issue by PotassiumK** [DDMAL/Pixel.js#19]
A possible way to bypass the limitation of large image sizes uploaded onto browsers.
The idea is to splice an image, retain its matrix position data, allow editing of the many cropped portions of the image and put it all together in the end.

Note: may not be the final solution

**Comment by fujinaga** [comment]
Have you discussed with Andrew about using Diva.js for Pixel.js?
Diva works on the idea that a user never sees more than what can be seen on the screen.

**Comment by ahankinson** [comment]
Commented on #23

**Comment by zeyadhazem** [comment]
Already implemented in Diva
