### ISSUE TITLE
Upload changes periodically to Rodan

### ISSUE THREAD

**Issue by zeyadhazem** [DDMAL/Pixel.js#21]
Use the REST API to communicate with Rodan and save changes to the image by uploading them periodically

**Comment by ahankinson** [comment]
Uploading what?

**Comment by zeyadhazem** [comment]
What we talked about yesterday. Uploading changes to the photo to Rodan, bit by bit while the user is editing or whole picture after they press submit.

**Comment by zeyadhazem** [comment]
Suggestion dropped. All changes to the image are applied when the user clicks on "Export As Matrix" Button, at the end of editing. This minimizes the unnecessary overhead while drawing.
