### ISSUE TITLE
Integrate Pixel.js with Diva.js

### ISSUE THREAD

**Issue by PotassiumK** [DDMAL/Pixel.js#23]
@ahankinson I remember you mentioning an issue with this integration but I forgot what you said.

**Comment by ahankinson** [comment]
You can use Diva.js to display and manipulate large images. Diva.js 6 is currently in development here:

https://github.com/DDMAL/diva.js/tree/develop-diva6

and contains significant changes to how Diva is instantiated and used. 

You can look at the `_filters.js` file for specific image manipulate algorithms in the Diva 6 version:

https://github.com/DDMAL/diva.js/blob/develop-diva6/source/js/plugins/_filters.js

Diva itself is a multi=page image viewer, but it can be used to display a "document" of a single image.

The advantage of using Diva is:

a) it knows how to transfer images efficiently. It interacts with an image server (IIP Image Server) to request only the tiles that are being viewed in the browser at a given time. 

b) it uses canvas, so the tiles that it does draw all behave as a single image. For example, it will request 4 x 256*256 tiles, but these will be reassembled into the browser (and can be manipulated) as a single canvas object.

c) you don't have to write zooming, panning, mobile device support, etc. That's all (more or less) done. 

You can interact with the Diva instance via the Diva API, so you can make Diva the "rendering engine" for a larger application that you build around it. 

My recommendation would be to start there.

**Comment by PotassiumK** [comment]
@zeyadhazem ^

**Comment by fujinaga** [comment]
Another advantage of using Diva is that you can learn about Diva and may be able to contribute to  the Diva development in the future.

**Comment by zeyadhazem** [comment]
Still need the approval of DDMAL/Diva.js#387 as well as fix ```disableScroll()``` method in diva

**Comment by zeyadhazem** [comment]
Still need the approval of DDMAL/diva.js#387 as well as fix disableScroll() method in diva

**Comment by PotassiumK** [comment]
o, this issue was more referring to the fact that we were maybe gonna make it part of diva. But now it's been decided to dev it as a plugin, it pretty much implies integration 🍡
