### ISSUE TITLE
Remove your python virtual environment

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/Pixel.js#24]
Maybe I didn't use enough "evers" in saying that you never commit it.

You should also figure out how to rewrite your history to remove it from all previous commits.

**Comment by ahankinson** [comment]
While you're at it, remove your `db.sqlite3` file, too.

**Comment by ahankinson** [comment]
And all `.pyc` files in the `__pycache__` directories.

**Comment by ahankinson** [comment]
And the `.idea` folder.

**Comment by zeyadhazem** [comment]
On it
