### ISSUE TITLE
Version of diva.js?

### ISSUE THREAD

**Issue by napulen** [DDMAL/Pixel.js#245]
I am trying to go through the installation process, cloned the latest diva.js and mounted Pixel.js on top of the plugins folder as mentioned.

A couple of things I notice:

The latest diva does not have a `diva.js/webpack.config.js` file. These are the files I am seeing
```
webpack.conf.coverage.js
webpack.conf.dev.js
webpack.conf.prod.js
webpack.conf.test.js
```
There is also no `source/css/diva.css` in the latest diva, just a `diva.less` which looks like a template

Am I missing something?

If diva has changed its core architecture, should we constrain Pixel.js to a specific version of diva.js?

**Comment by PotassiumK** [comment]
Make sure you are using Diva.js 6, the version currently on develop.
iirc, there's a css file that you indeed have to manually migrate/paste into the correct folder.

**Comment by napulen** [comment]
Diva.js 6 does have the css and config files, there wasn't any need to copy anything else, got pixel working on the browser now 8).
