### ISSUE TITLE
Do you need a Django server?

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/Pixel.js#25]
The front-end will be written entirely in JavaScript. The back-end will, eventually, be integrated with Rodan. You do not need all of the things that Django provides (a database backend, integration with Solr, etc.) so the server requirements are relatively simple.

You may also be able to get away with just using the built-in Python webserver for serving static files:

`$> python3 -m http.server`

will start a very basic HTTP server running on port 8000 by default.

**Comment by zeyadhazem** [comment]
Sure no Django then! We will start from Diva

Thanks for the advice
