### ISSUE TITLE
Setup standalone Pixel in GitHub pages

### ISSUE THREAD

**Issue by EricHanLiu** [DDMAL/Pixel.js#250]
Maybe with latest Diva 6 changes

**Comment by EricHanLiu** [comment]
Should be done in https://github.com/DDMAL/Pixel.js/tree/gh-pages (http://ddmal.github.io/Pixel.js)

Waiting a bit for the page to be setup

**Comment by vigliensoni** [comment]
Do you mean:

https://ddmal.github.io/Pixel.js

**Comment by EricHanLiu** [comment]
Yeah whoops

**Comment by EricHanLiu** [comment]
Still not live for some reason

**Comment by vigliensoni** [comment]
The currrent version is searching for resources at

ddmal.github.io/build/...

**Comment by EricHanLiu** [comment]
Fixed

Might still not work for a few minutes, hasn't refreshed yet

**Comment by vigliensoni** [comment]
404 when trying to find iiifv2.json inside ddmal.github.io/Pixel.js/test/

**Comment by EricHanLiu** [comment]
Yeah that's an old error, it's been changed already just not refreshed yet, latest commit hasn't been detected yet

**Comment by EricHanLiu** [comment]
Works now!
