### ISSUE TITLE
Overlaid images on screen when "Export as image Data PNG"

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/Pixel.js#254]
When exporting as image Data PNG, the region being exported is overlaid on top of the zoomed image

![screen shot 2018-11-20 at 12 01 15 pm](https://user-images.githubusercontent.com/492229/48790041-740fcf00-ecbc-11e8-8783-3d9bb91ba6d7.png)

**Comment by zeyadhazem** [comment]
@vigliensoni Bug... or feature? ;P
