### ISSUE TITLE
Make tutorial videos and images available

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/Pixel.js#255]
As of now, the tutorial images and videos are not being served.

![Screen Shot 2020-01-21 at 11 31 07 AM](https://user-images.githubusercontent.com/492229/72823336-8af3dd80-3c41-11ea-8ee1-1497fb4d078b.png)

This behaviour happens in Firefox, Chrome, and Safari when launching Pixel as a Rodan job. There are no errors in the JS console.

**Comment by vigliensoni** [comment]
This is actually happening even in the Github instructions (https://github.com/DDMAL/Pixel.js/wiki/How-to-use-Pixel.js), and so it should be that the media is not available.

**Comment by JRegimbal** [comment]
Was it @PotassiumK or someone else's giphy account or the lab's? I can't find backups of the gifs on the share.

**Comment by vigliensoni** [comment]
I left the images and videos I have inside  ```Share/Drop/pixel/```

**Comment by JRegimbal** [comment]
Thanks. I've converted the necessary videos to gifs and added them to the wiki under the `assets` folder. We should be able to link to them through the wiki for Pixel itself.
