### ISSUE TITLE
Install Diva and figure out API

### ISSUE THREAD

**Issue by PotassiumK** [DDMAL/Pixel.js#26]
Learn about the Diva API and how to interact with through this project

**Comment by zeyadhazem** [comment]
@ahankinson the current release is Diva 5, are there gonna be any compatibility problems with the API after the release of Diva 6 or are the changes to Diva 6 only going to be internal? (Thus we can focus our efforts mainly on understanding the API)

**Comment by ahankinson** [comment]
There will probably be problems, yes. The decision you need to make then is whether you build your application on top of software that will very soon on be obsolete (diva 5) or to contribute to making diva 6 more robust.

**Comment by fujinaga** [comment]
I would recommend going with Diva 6.

**Comment by ahankinson** [comment]
Just FYI, though: Diva 6 is pretty unstable at the moment. It's a pretty big update, but worthwhile I think:
 - Move everything to ES6 with webpack
 - Move all icons to SVG (this means that they can be embedded in the code, so there is only one file to download, the `diva.js` file).
 - Removing the old Diva JSON format in favour of IIIF manifests only, with a new IIIF manifest parser that supports multiple canvases (i.e., multiple image files for each page; useful for multi-spectrum imaging)

But there are a few issues with it at the moment that may need to get sorted out. I've been working on it in my spare time.
