### ISSUE TITLE
Understand how to write a Diva Plugin

### ISSUE THREAD

**Issue by PotassiumK** [DDMAL/Pixel.js#28]
See if a plugin can cover the scope of the editing tool that Pixel needs to be

**Comment by ahankinson** [comment]
This is a simple example of how a Diva plugin for Diva 6 can be written:

https://github.com/DDMAL/diva.js/blob/develop-diva6/source/js/plugins/download.js

The image manipulation plugin in that same folder is an example of how to write a more complex plugin.

**Comment by zeyadhazem** [comment]
Affiliated with #33
