### ISSUE TITLE
Create a Rodan Wrapper

### ISSUE THREAD

**Issue by zeyadhazem** [DDMAL/Pixel.js#29]
Find a way to link Diva to Rodan and accept images as an input (Maybe by using Rodan's API to set it as our image server?)

**Comment by ahankinson** [comment]
Rodan usually has an IIP image server configured. As of Diva 6 you will need to load images using a IIIF Presentation API manifest, so that will need to be generated on the fly. Perhaps there can be a Rodan job to do that?

**Comment by zeyadhazem** [comment]
Created in [diva_wrapper repo](https://github.com/DDMAL/diva_wrapper). Only supports 3 inputs and 3 outputs for now. Still needs optimizations to improve modularity.
