### ISSUE TITLE
How does one run Diva6 for testing? 

### ISSUE THREAD

**Issue by PotassiumK** [DDMAL/Pixel.js#30]
I have Diva code on IntelliJ and I would like to run it to see how the new plugin looks like so far. How would I go about doing that? Please help!

**Comment by ahankinson** [comment]
`git pull` (get the latest changes on the develop-diva6 branch
`npm install` (if you haven't already installed the dependencies)
`npm install -g gulp webpack` (if you don't already have gulp and webpack installed)
`gulp` will lint and compile the code, and run a webserver on localhost:9001, serving the index.html file.

**Comment by ahankinson** [comment]
Note, though, that rendering page images is currently broken. It will only render half of one. I'm trying to find some time to sort that out.

**Comment by ahankinson** [comment]
(or, if you want to sort it out, go ahead!)

**Comment by PotassiumK** [comment]
Thank you!
The index file also references `href="build/css/diva.css"` but there is no css file currently in build. I copied the css file in source to the build file and it somewhat removed the errors; I just have to figure out how to make the images actually render on the browser now. It currently displays a very blank window but at least we know it manages to fetch the simssa manuscripts.

**Comment by PotassiumK** [comment]
Also, we're very highkey relying on you to sort out the rendering problem!

**Comment by ahankinson** [comment]
And I'm highly relying on you to get up to speed on how Diva works to help me out.

**Comment by PotassiumK** [comment]
I want to, but I really did not manage much trying to do that yesterday. Where do I start looking to understand why there's a rendering problem?

**Comment by ahankinson** [comment]
In your browser's development console. You can start by just figuring out how that works, and how to find the line where the problem occurs. You can then move on to figuring out how the JS debugger works. You can set breakpoints by including the command `debugger;` in your JS code. When the browser goes to execute that line, it will stop and let you inspect the state of the application.

**Comment by PotassiumK** [comment]
Currently the development console displays no errors, making debugging much more difficult.

**Comment by ahankinson** [comment]
It should. It's giving me an error.

**Comment by PotassiumK** [comment]
Well I did change some references to fix the initial errors and now there are no errors, to be more precise.

**Comment by zeyadhazem** [comment]
There's also a build error that happens when you call gulp:

[14:28:22] 'lint-src' errored after 21 s
[14:28:22] Error in plugin 'gulp-jshint'
Message:
    JSHint failed for: source/js/interpolate-animation.js, source/js/parse-iiif-manifest.js, source/js/renderer.js, source/js/plugins/_filters.js, source/js/utils/dragscroll.js

Maybe this is causing us not to see what you're seeing?

**Comment by PotassiumK** [comment]
Update: we are seeing what you're seeing

**Comment by ahankinson** [comment]
Those are lint errors (through JSHint). I get the same ones.
