### ISSUE TITLE
Render Diva6 images in the browser

### ISSUE THREAD

**Issue by PotassiumK** [DDMAL/Pixel.js#32]

**Comment by PotassiumK** [comment]
@ahankinson on line 212 of renderer.js
`this._compositeImages[pageIndex].getTiles(this._zoomLevel).forEach((source) =>`

As I understand it, this line gets the tiles at the current zoom level from the composite images. What does `(source)` refer to?

**Comment by PotassiumK** [comment]
Also, is it normal that we can't see the assets folder containing diva.js within intelliJ?

**Comment by zeyadhazem** [comment]
Duplicate of DDMAL/diva.js#378
