### ISSUE TITLE
Rewrite a modified highlight plugin for Diva 6

### ISSUE THREAD

**Issue by zeyadhazem** [DDMAL/Pixel.js#33]
The highlight plugin in Diva 5 was very useful to the purposes of drawing on a document. However it needs some work, since the rendering method in Diva 5 was changed. Also it should be able to retrieve information about the pixels it is highlighting (page number, pixel x and y positions)

**Comment by ahankinson** [comment]
In the previous versions of Diva we used individual `div`s as tiles, and the highlights were implemented as other `div`s drawn on top of them. 

In Diva, an important thing to remember is that it only keeps ~3-4 pages on the DOM at any given time. At no point (unless the document is less than 3-4 pages long) is the entire document loaded into the browser.

The way the highlights worked in the older version was that the zones to be highlighted were stored in a hash based on the page identifier. When that page was loaded, the zone `div`s were drawn on top of that page. When the page was scrolled out of view, all the highlight `div`s would be deleted from the DOM.

In the new version of Diva we use the Canvas for rendering the page images. The `div` method of drawing highlights no longer really works well and there is a noticeable lag between the alignment of the highlight and page image when the user scrolls.

So the best way to implement this is to composite the highlights directly on to the page image when the page image is loaded into the DOM, and to not try and re-implement the `div`-based highlights.

**Comment by PotassiumK** [comment]
So for future reference, doesn't this mean `div`-based layers would also be off the table?

**Comment by ahankinson** [comment]
Do you think they would be an appropriate approach?

**Comment by PotassiumK** [comment]
Putting canvas elements on top of the existing canvases was the original thought.

**Comment by ahankinson** [comment]
Why not composite boxes directly on one canvas?

**Comment by zeyadhazem** [comment]
I am still a little unclear on how to instantiate the already existing plugins such as enable download and canvas. In diva 5 it was just by including enableDownload (for example) while instantiating diva in the HTML file. According to the documentation, plugins in Diva 6 should be registered in the global context as part of the Diva namespace, which is already done in with the download plugin.

```javascript
(function (global)
{
    global.Diva.DownloadPlugin = DownloadPlugin;
})(window);
```

If I understand correctly this means that they're ready for use but they're uninstantiated. To instantiate it I am doing the following: 

```javascript
var diva = new Diva('diva-wrapper', {
                objectData: "https://images.simssa.ca/iiif/manuscripts/cdn-hsmu-m2149l4/manifest.json",
                plugins: [Diva.DownloadPlugin]
            });
```

But it still doesn't seem to work, I can't see the download icon around the pages. Is there something I am doing wrong?

**Comment by PotassiumK** [comment]
Follow-up of DDMAL/diva.js#354

**Comment by ahankinson** [comment]
It may be that it's working, it's just the icon isn't being drawn. Did you check that?

**Comment by zeyadhazem** [comment]
No my only check was if it goes to the constructor of the DownloadPlugin class, but that doesn't seem to be the case.

**Comment by zeyadhazem** [comment]
Opened an issue in Diva DDMAL/diva.js#383

**Comment by zeyadhazem** [comment]
Task is too general, will be broken down into more specific ones
