### ISSUE TITLE
Make a square drawn on top of a page in Diva resize correctly after zooming

### ISSUE THREAD

**Issue by zeyadhazem** [DDMAL/Pixel.js#35]
The coordinates of the origin of the square as well as its width and height are all relative to the zoom level of the page.

**Comment by ahankinson** [comment]
If it's a question of scaling positions from the full size to a given zoom level, there are Diva functions to help with that:

https://github.com/DDMAL/diva.js/blob/develop-diva6/source/js/diva.js#L1404-L1447

**Comment by zeyadhazem** [comment]
Pushed
