### ISSUE TITLE
Function passed to Diva.Events.subscribe cannot access properties or methods of the class

### ISSUE THREAD

**Issue by zeyadhazem** [DDMAL/Pixel.js#43]
Basically if we're inside, we cannot use the keyword "this" to access any properties or methods of the instance of the class. This might be happening because the subscription is only called once (wether in the constructor or inside a method) so no continuous update (kind of stuck in the when it was called)

Maybe the fix should be that some other entity outside of the plugin subscribes to that event and then calls the methods inside to plugin to perform the change?

**Comment by ahankinson** [comment]
https://github.com/DDMAL/diva.js/blob/develop-diva6/source/js/utils/events.js#L31

See argument 3.

**Comment by zeyadhazem** [comment]
I am still having trouble with this.
This is how I am publishing from viewer-core.js
```
onVisibleTilesDidLoad: (pageIndex, zoomLevel) =>
{
    this.publish('VisibleTilesDidLoad', [pageIndex, zoomLevel], self.Diva.PixelPlugin);
}
```

And this is how I am subscribing inside my pixel.js
```
Diva.Events.subscribe('VisibleTilesDidLoad', function () {console.log(this)}, self.Diva.PixelPlugin);
```

I have played around with it, but it always seems that this returns a Diva instance

**Comment by zeyadhazem** [comment]
Also, self.Diva.PixelPlugin returns a function and not a class so I can't access its properties

**Comment by zeyadhazem** [comment]
Okay all good! It works now! Thanks!

**Comment by ahankinson** [comment]
How did you get it to work?

**Comment by zeyadhazem** [comment]
I passed an instance of the class to the subscriber method, the following way
```
subscribeToEvent(highlighted){
        let instance = this;

        let handle = Diva.Events.subscribe('VisibleTilesDidLoad', function(args){
            instance.drawHighlights(highlighted, args);
        });
        return handle;
    }
```
This is the entry point to the plugin from the subscriber. Everywhere else in the code I can use the keyword "this" with no problem

Edit: ... with the curly brackets on a new line 😅

**Comment by ahankinson** [comment]
Why don't you just pass in `this`?

`Diva.Events.publish('SignalType', [args], this);`

**Comment by ahankinson** [comment]
Also you could do:

```
Diva.Events.subscribe('VisibleTilesDidLoad', (args) =>
{
    this.drawHighlights(stuff, args);
});
```

With arrow functions, `this` is scoped to the outer object; with `function` you need to explicitly pass in the `this` scope, otherwise it's scoped to the function:

```
Diva.Events.subscribe('VisibleTilesDidLoad', function (args)
{
    this.drawHighlights(stuff, args);
}, this);
```

**Comment by zeyadhazem** [comment]
When I passed this from inside viewer core it just passed the viewer core itself, which is not really what I needed. By default if nothing is passed for scope, it passes a Diva instance. So passing this wasn't really useful. The second method ``` (args) => { this.draw() } ``` worked!! Thanks!
