### ISSUE TITLE
Unable to call diva renderer within pixel function

### ISSUE THREAD

**Issue by PotassiumK** [DDMAL/Pixel.js#49]
Probably did not manage to call diva properly. Mostly an issue  (very small one) so I don't forget to fix this Monday.

**Comment by zeyadhazem** [comment]
You can use this.core.getSettings().renderer

**Comment by PotassiumK** [comment]
Yeah I'm using `this.core.getSettings().renderer.layout.dimensions.height` for the matrix. Not sure that's the actual height though. `3339592` is its value at 6x zoom.
