### ISSUE TITLE
Implement a local Django MTV web app skeleton

### ISSUE THREAD

**Issue by PotassiumK** [DDMAL/Pixel.js#5]
A functional MVC(MTV) web app with simple view with only a title page

**Comment by musicus** [comment]
How can you break this task down into smaller tasks?

**Comment by zeyadhazem** [comment]
• Use the base project from the tutorials week to provide basic rendering templates over which HTML components can be added.
• Import JS modules.
• Design a Model and provide its functionality in the View.

**Comment by zeyadhazem** [comment]
Dropping this, development will be done purely in JS as a plugin for Diva. See #33
