### ISSUE TITLE
Create copy of base matrix on zoom request

### ISSUE THREAD

**Issue by PotassiumK** [DDMAL/Pixel.js#50]
When the user zooms, a new matrix that is of the size of the zoom level must be created in order to map the zoom-level-specific changes. Those smaller matrices need to eventually be mapped onto the base matrix which should contain all layer information.

**Comment by zeyadhazem** [comment]
Suggestion dropped, more efficient alternative is to directly map to the base matrix (at max width) which represents the image at its highest resolution

**Comment by zeyadhazem** [comment]
Reopened since this might be a useful optimization task
