### ISSUE TITLE
Control layer depth (move forward, move backward)

### ISSUE THREAD

**Issue by PotassiumK** [DDMAL/Pixel.js#54]
Implement control of layers and their depth compared to each other.
Typical keyboard shortcuts: 
ctrl/cmd+shift+] : Send layer to top of stack
ctrl/cmd+shift+[ : Send to bottom of stack
ctrl/cmd+] : Move layer up
ctrl/cmd+[ : Move layer down

**Comment by musicus** [comment]
🔥
