### ISSUE TITLE
Swap layers' UI order

### ISSUE THREAD

**Issue by PotassiumK** [DDMAL/Pixel.js#70]
Currently the first layer is the one in the back-most layer and the last layer at the bottom of the array is the layer that covers all other layers.
For a more intuitive UI, that order should be swapped, ie the first layer needs to be on top.

**Comment by PotassiumK** [comment]
@zeyadhazem why To Do?

**Comment by zeyadhazem** [comment]
It wasn't fully working before, no?

**Comment by PotassiumK** [comment]
Hmmm this was just supposed to be about displaying the layers as 5, 4, 3, 2, 1 instead of 1, 2, 3, 4, 5.
