### ISSUE TITLE
Optimize the runtime performance of Pixel.js

### ISSUE THREAD

**Issue by zeyadhazem** [DDMAL/Pixel.js#72]
The following are suggestions to optimize Pixel:
<ul>
<li> Fix DDMAL/diva.js#380 </li>
<li> Create a clone canvas to draw on top of it instead of drawing on the same canvas as Diva </li>
<li> The good thing about having a separate canvas is that there will be no need to redraw the underlying diva image after undoing an action. </li>
<li> Instead of redrawing every path and shape at every scroll, try to find a better way? </li>
</ul>

**Comment by PotassiumK** [comment]
This is a big issue! ☣️ 
Gonna be separated into smaller issues when the time comes. 👀
