### ISSUE TITLE
Stylize Pixel.js

### ISSUE THREAD

**Issue by zeyadhazem** [DDMAL/Pixel.js#79]
Make the tools look much nicer, lay the toolbox on top of Diva

**Comment by PotassiumK** [comment]
I like the toolbox underneath Diva... Let's chat with Vi-An before engaging in this.

**Comment by zeyadhazem** [comment]
Created a preliminary css file that stylizes the layers view. The file will be populated as the project progresses (stylize tools view, etc...)
