### ISSUE TITLE
Create a "New Project" functionality

### ISSUE THREAD

**Issue by PotassiumK** [DDMAL/Pixel.js#8]
Create a single blank layer as a basis for future multi-layer functionality

**Comment by ahankinson** [comment]
I would be careful here. Anything like project management, etc. is all built into Rodan. You're just doing the interface for it. Don't build more than you need.

**Comment by PotassiumK** [comment]
Uploading an image file for editing on the interface is by extension a "New Project" though. Is it wrong to think that it is part of the interface? Or do you mean that all image files will be taken from Rodan, so we do not need to think about uploading from a local drive?

**Comment by ahankinson** [comment]
Yes, it is wrong. The image will come in to your interface from some other process; the only reason you would need to 'upload' an image is for local development.

**Comment by PotassiumK** [comment]
To be completely sure, are you are saying that Pixel will not support local development?

**Comment by ahankinson** [comment]
No, I'm not saying that. You will need to do local development while you're working on the user interface. Your project should take an image as input and produce output suitable to being used in a Rodan workflow, but you don't actually need to develop your tool within a Rodan environment (yet).

Check out the DDMAL/Interactive-Classifier project for an example of how this might work. The code for the Rodan interaction is in the 'rodan_job' folder, but most of the rest of the application is in the 'frontend' folder.

**Comment by PotassiumK** [comment]
Download plugin in Diva takes care of this.

**Comment by PotassiumK** [comment]
Essentially #29
