### ISSUE TITLE
Create script to link Pixel with Diva

### ISSUE THREAD

**Issue by zeyadhazem** [DDMAL/Pixel.js#81]
In order for pixel to work, there are some changes that need to be done to the webpack.config.js file as well as other files. The script can also compile and run the app on the user's localhost.

**Comment by PotassiumK** [comment]
Is this not already done? As long as pixel is in the plugin file, gulping diva itself should be sufficient, given that the few lines that enable the pixel plugin are included in diva's `webpack.config.js`

I guess we could also have people install our own `webpack.config.js` and swap it with whatever diva has.

**Comment by PotassiumK** [comment]
Hand-in-hand with #23
