### ISSUE TITLE
Implement an "Export as..." button

### ISSUE THREAD

**Issue by PotassiumK** [DDMAL/Pixel.js#9]
The export functionality includes exporting as an image (expected improvement: export by layer functionality) or exporting the encoded matrix.

**Comment by ahankinson** [comment]
Remember that you are not creating a full application; you are creating a component in a larger workflow. The primary goal is to ensure that a server has an image that it can use to do further processing on. Once the server processes an image it will be available to download.

As a Rodan job, you can provide multiple "Output ports", one for each layer. This can be configured in the Rodan client.

Remember that if you adopt a high-resolution image viewer like Diva, you may not have the entire image loaded in the browser for the user to download.

**Comment by zeyadhazem** [comment]
The export function is going to be used only for testing purposes. Although it can still be a good functionality to implemented combined with #8 to store the progress locally by the user and then giving him the choice to continue working. This of course clashes with #21 which assumes that we will upload changes periodically to Rodan thus not requiring any changes to be done locally.
But again, the main idea from this is testing.

**Comment by PotassiumK** [comment]
The main idea of this is truly not limited to testing after all!
